"""Add PDF document and extracted data tables

Revision ID: 05c60bdf9d75
Revises: 1a31ce608336
Create Date: 2025-10-24 11:31:02.718193

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '05c60bdf9d75'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdfdocument',
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdfdocument_filename'), 'pdfdocument', ['filename'], unique=False)
    op.create_index(op.f('ix_pdfdocument_owner_id'), 'pdfdocument', ['owner_id'], unique=False)
    op.create_table('extracteddata',
    sa.Column('store_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('store_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('store_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('receipt_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cashier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('register_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('transaction_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subtotal', sa.Numeric(), nullable=True),
    sa.Column('tax_amount', sa.Numeric(), nullable=True),
    sa.Column('total_amount', sa.Numeric(), nullable=True),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['pdfdocument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracteddata_document_id'), 'extracteddata', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracteddata_document_id'), table_name='extracteddata')
    op.drop_table('extracteddata')
    op.drop_index(op.f('ix_pdfdocument_owner_id'), table_name='pdfdocument')
    op.drop_index(op.f('ix_pdfdocument_filename'), table_name='pdfdocument')
    op.drop_table('pdfdocument')
    # ### end Alembic commands ###
