"""add product catalog system

Revision ID: 0fe14e75d90c
Revises: 5de78f925a37
Create Date: 2025-10-29 10:38:42.891294

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0fe14e75d90c'
down_revision = '5de78f925a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
