"""add_tax_breakdown_to_extracted_data

Revision ID: 5de78f925a37
Revises: 155751ad82b0
Create Date: 2025-10-26 13:41:38.142855

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5de78f925a37'
down_revision = '155751ad82b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracteddata', sa.Column('tax_breakdown', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extracteddata', 'tax_breakdown')
    # ### end Alembic commands ###
